### ISSUE TITLE
Options section is more rigidly defined than other docopt implementations

### ISSUE THREAD

**Issue by caldwell** [docopt/docopt.php#15]
Here is a test program that works:
```php
<?php
require 'vendor/autoload.php';

$doc = <<<DOC
Usage:
    test [-t <ttt>]... [-x <xxx>] [<yyy>]...

Options:
    -t <arg>   Y
    -x <xxx>   X

DOC;

$args = (new \Docopt\Handler)->handle($doc);
print_r($args);
```

Here's the output:
```
$ php test.php -t a -t b -x xxx 1 2 3 4
Docopt\Response Object
(
    [status] => 0
    [output] =>
    [args] => Array
        (
            [-t] => Array
                (
                    [0] => a
                    [1] => b
                )

            [-x] => xxx
            [<yyy>] => Array
                (
                    [0] => 1
                    [1] => 2
                    [2] => 3
                    [3] => 4
                )
        )
)
```

But if I add a blank line in the options list then it doesn't work:
```
Options:
    -t <arg>   Y

    -x <xxx>   X
```
The output becomes this: (note the `-x` has reverted to a flag option and its parameter goes into `<xxx>` instead)
```
$ php test.php -t a -t b -x xxx 1 2 3 4
Docopt\Response Object
(
    [status] => 0
    [output] =>
    [args] => Array
        (
            [-t] => Array
                (
                    [0] => a
                    [1] => b
                )
            [-x] => 1
            [<xxx>] => xxx
            [<yyy>] => Array
                (
                    [0] => 1
                    [1] => 2
                    [2] => 3
                    [3] => 4
                )
        )
)
```

This also doesn't work:
```
Options in common:
    -t <arg>   Y
    -x <xxx>   X
```
The output for this case: (neither option acts like it's declared)
```
php test.php -t a -t b -x xxx 1 2 3 4
Docopt\Response Object
(
    [status] => 0
    [output] =>
    [args] => Array
        (
            [-t] => 2
            [<ttt>] => Array
                (
                    [0] => a
                    [1] => b
                    [2] => xxx
                    [3] => 1
                    [4] => 2
                    [5] => 3
                    [6] => 4
                )

            [-x] => 1
            [<xxx>] =>
            [<yyy>] => Array
                (
                )
        )
)
```

Both of those cases work correctly in the [reference implementation](http://try.docopt.org/?doc=Usage%3A%0D%0A++++test+%5B-t+%3Cttt%3E%5D...+%5B-x+%3Cxxx%3E%5D+%5B%3Cyyy%3E%5D...%0D%0A%0D%0AOptions+in+common%3A%0D%0A++++-t+%3Carg%3E+++Y%0D%0A%0D%0A++++-x+%3Cxxx%3E+++X%0D%0A%0D%0A&argv=test+-t+a+-t+b+-x+xxx+1+2+3+4)

**Comment by shabbyrobe** [comment]
Neither of these work in the reference implementation either.

```
$ python v1.py -t a -t b -x xxx 1 2 3 4
{'-t': ['a', 'b'],
 '-x': 'xxx',
 '<yyy>': ['1', '2', '3', '4']}

$ python v2.py -t a -t b -x xxx 1 2 3 4
{'-t': ['a', 'b'],
 '-x': True,
 '<xxx>': 'xxx',
 '<yyy>': ['1', '2', '3', '4']}
```

The second issue is that `Options in common:` is not parsed as an options section. docopt is only looking for `options:` as the section header. So when you use a different section header, it falls back to your usage line for the option spec.

**Comment by caldwell** [comment]
I see, I was confused because the php code is ahead of python code, release-wise. The python still has 0.6.2 in pip and on the [try docopt site](http://try.docopt.org/), but the HEAD of the [git repo](https://github.com/docopt/docopt) behaves the way you describe (the same as the latest php release).

**Comment by shabbyrobe** [comment]
The PHP version has a separate version number to the python version. It was a tricky decision to make but managing the port's versioning has been better this way than it was when I tried to keep them in lock-step. It's covered in the readme, but it could probably be a bit clearer:

> This port has been marked version 1.0. It is based on the Python version at commit a093f938b7f26564434f3c15a1dcc39e017ad638 (labelled 0.6.2).
