### ISSUE TITLE
Readable coding style

### ISSUE THREAD

**Issue by szepeviktor** [docopt/docopt.php#23]
PSR-12 may help structuring and keeping the code nice and readable.

**Comment by shabbyrobe** [comment]
Hello, thanks for the suggestion.

There are very good reasons for the coding style. From the README:

> This is a straight PHP transliteration of Vladimir Keleshev's brilliant docopt Python library. There are a few artefacts in the code as a result that may seem inefficient and non-idiomatic to PHP, this has been done to make integrating changes more efficient.

Having said that, if there was sufficient uptake of PSR-12 in the community, some things like control structures, bracing styles, might be able to be changed without compromising the above. From what I can see, the code isn't too far from PSR-12 as it is, so I'll close this for now. If there's something more concrete I will consider it, but I would probably decline a PR with only style changes at this point.
