### ISSUE TITLE
No installable candidates for 3 years - how so?

### ISSUE THREAD

**Issue by OnkelTem** [docopt/docopt.php#24]
So I cannot install the latest 1.0.3 version because of some HHVM.

I'm a PHP developer with 15+ years of exp and honeslty - I don't know what is HHVM and don't have any desire to know. Don't take me wrong, usually I have a decent setup on my machines and they've been running Linx Debian and then Ubuntu for 20 years. But now I cannot install some PHP package because of some HHVM which I never used. I just don't get what can be so wrong about PHP that one has to install some virtual machine to run it?

From what I see the version 1.0.3 was released back in 2017-03-28 08:43 UTC, i.e. almost 3 years ago. The funny thing - I've been using DocOpt for about a year and haven't got any problems with it. This is because I was and am still using its **dev** version. It's just that now I decieded to *realease* my product and discovered that I CANNOT do this: I have to use stable versions but you do not provide any working one.

Please give us **something**. DocOpt rocks. And doesn't need some weird HHVMs to run.

**Comment by OnkelTem** [comment]
I just went to see, PHP 5.3 was released TEN YEARS AGO.

**Comment by shabbyrobe** [comment]
Hello OnkelTem. You don't need HHVM to run this; HHVM is an old alternative PHP runtime that Facebook unleashed on the world then recently abandoned.

Can you paste me the text of the error you're experiencing? I'll have a look now and see if I can reproduce in the meantime.

**Comment by OnkelTem** [comment]
Hi Blake!

I suppose it should be reproducible right away, w/o any preparations.
Try this one:
```
composer require docopt/docopt:1.0.3 --no-interaction
```

**Comment by shabbyrobe** [comment]
Great, thanks for the details! Investigating now.

**Comment by shabbyrobe** [comment]
Looks like my last commit fixed the install problem, but requires a version nudge:

> composer require docopt/docopt:1.0.4 --no-interaction

Travis has blown up again though, as it always does whenever I have to make even the tiniest change to this repo 😆. I'll leave the issue open until that's fixed (or until you tell me the above didn't fix your problem!)

**Comment by shabbyrobe** [comment]
OK all the tests are passing now, I no longer see your issue when I install, so I'm gonna close. I think it must've been a misconfiguration in a transitive dependency.

Thank you very much for letting me know, sorry this blew up your install!

**Comment by OnkelTem** [comment]
It worked, thank you very much!
